In [13]:
import pandas as pd             

## loading the ratings into a dataframe
## having index_col='people' makes the their names as the row labels instead of just basic numbers

df = pd.read_csv('Moviesnpeople.csv', index_col='People') 

print(" Original Movei Ratings")
display(df)

## now we show the average ratings for each person and for each movie 
## axis=1 calculates the average horizontally 
## and axis=0 calculates the average vertically

print("\n Average Ratings for Each User")
display(df.mean(axis=1).round(2).reset_index(name='Average Rating'))

print("\n Average Rating by Movie")
display(df.mean(axis=0).round(2).reset_index(name='Average Rating')) 

## creating a dataframe with normalized ratings also having a min-max scrollng
## the formula is (value - min) / (max - min)
##  We transpose the dataframe (df.T) to easily do the math per user, then transpose back
df_norm = (df.T - df.T.min()) / (df.T.max() - df.T.min())
df_norm = df_norm.T

print("\n Normalized Ratings")
display(df_norm.round(2))

print("\n Average Normalized Rating by User")
display(df_norm.mean(axis=1).round(2).reset_index(name='Avg Normalized Rating'))

print("\n Average Normalized Rating by Movie")
display(df_norm.mean(axis=0).round(2).reset_index(name='Avg Normalized Rating'))

 Original Movei Ratings

,Spider-Man: Brand New Day,The Odyssey,Prime Time,Thunderbolts,All Quiet on the Western Front,Fury
People,,,,,,
Me,5,4,2,4,4,5
Larry,4,5,4,3,3,5
Brother,5,4,2,3,4,4
Olex,5,4,2,4,3,4
David,4,3,2,1,1,2

 Average Ratings for Each User

    People  Average Rating
0       Me            4.00
1    Larry            4.00
2  Brother            3.67
3     Olex            3.67
4    David            2.17

 Average Rating by Movie

                            index  Average Rating
0       Spider-Man: Brand New Day             4.6
1                     The Odyssey             4.0
2                      Prime Time             2.4
3                    Thunderbolts             3.0
4  All Quiet on the Western Front             3.0
5                            Fury             4.0

 Normalized Ratings

,Spider-Man: Brand New Day,The Odyssey,Prime Time,Thunderbolts,All Quiet on the Western Front,Fury
People,,,,,,
Me,1.0,0.67,0.00,0.67,0.67,1.00
Larry,0.5,1.00,0.50,0.00,0.00,1.00
Brother,1.0,0.67,0.00,0.33,0.67,0.67
Olex,1.0,0.67,0.00,0.67,0.33,0.67
David,1.0,0.67,0.33,0.00,0.00,0.33

 Average Normalized Rating by User

    People  Avg Normalized Rating
0       Me                   0.67
1    Larry                   0.50
2  Brother                   0.56
3     Olex                   0.56
4    David                   0.39

 Average Normalized Rating by Movie

                            index  Avg Normalized Rating
0       Spider-Man: Brand New Day                   0.90
1                     The Odyssey                   0.73
2                      Prime Time                   0.17
3                    Thunderbolts                   0.33
4  All Quiet on the Western Front                   0.33
5                            Fury                   0.73

## Conclusions - Advantages and Disadvantages of Normalization

## Advantages:
Normalizing data (scaling it from 0 to 1) is incredibly useful for adjusting to different persons baseline grading behaviors. A harsh critic might never give a movie a 5, treating a 4 as an absolute masterpiece. Meanwhile, a generous reviewer might hand out 5s to almost everything, treating a 3 as terrible. By normalizing the data on a per person basis, we even things out. A 1.0 represents that specific persons's absolute favorite movie, and a 0.0 represents their least favorite, regardless of whether their original scores were grouped between 2-4 or 4-5. This gives a much more specific figure when representing true ratings.

## Disadvantages:
The main drawback of normalization is that it destroys the absolute magnitude of the scores. If a person watches five incredible movies and rates them all 4s and 5s, the math forces their lowest rated ones to become a 0.0. Looking only at the normalized data, an algorithm would if not tweaked enough incorrectly assume the person absolutely hated that movie, when in reality, they just liked it slightly less than a so called perfect score. Normalization exaggerates tiny differences in tightly grouped data, completely removing the context of the overall positive or negative sentiment.